name: Docker Multi-Architecture Separate Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: self-hosted
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up QEMU for architecture support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Configure Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Extract Architecture-Specific Metadata
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest-${{ matrix.platform == 'linux/amd64' && 'x86' || 'arm' }}

      # 6. Build and Push Architecture-Specific Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
